-- 0022_curve_walkthrough_seed.sql
-- Curve Birtinya: 13 reporting sections and 176 standing questions, each anchored to the
-- Caretaking and Letting Agreement dated 29 October 2021 (scheme 54762).
-- Per 0019 these are per-building DATA in the committee's own words, each carrying a generic
-- duty_category so cross-building reporting keeps working. Questions deactivate, never delete.
-- The generic 22-item checklist is deactivated, not removed: Curve's three completed walks
-- have walkthrough_results rows pointing at it.

insert into public.walkthrough_finding_counters (building_id, ref_prefix, last_seq)
values ('ecd3d712-c949-4dec-b20c-9a5d36df0eb6'::uuid, 'CB', 0)
on conflict (building_id) do update set ref_prefix = excluded.ref_prefix;

create unique index if not exists walkthrough_sections_bld_name
  on public.walkthrough_sections (building_id, name);
create unique index if not exists walkthrough_items_bld_item
  on public.walkthrough_items (building_id, item);

update public.walkthrough_items set active = false
 where building_id = 'ecd3d712-c949-4dec-b20c-9a5d36df0eb6'::uuid and section_id is null;

insert into public.walkthrough_sections
  (building_id, name, duty_category, duty_reference, zone, route_sort, sort)
select 'ecd3d712-c949-4dec-b20c-9a5d36df0eb6'::uuid, v.name, v.cat, v.ref, v.zone, v.route, v.sort from (values
  ('Entrances, Reception Foyers and Lifts','entrances_foyers_lifts','Sch 1: Entrance, Reception Foyers and Lifts; Car Parks, Driveways and Entrances','West Tower entry · East Tower entry · ground foyers · lift cars · basement lift foyers',30,10),
  ('Upper Residential Foyers and Level Refuse Rooms','upper_foyers','Sch 1: Upper Residential Foyers','All residential levels, both towers',70,20),
  ('Car Parks, Driveways and Entrances','car_parks_driveways','Sch 1: Car Parks, Driveways and Entrances','Visitor car park · basement · driveways · Prosperity Drive and Mantra Esplanade approaches',10,30),
  ('Rubbish Collection and Refuse Rooms','rubbish_collection','Sch 1: Rubbish Collection; cl 3.9','West Tower refuse · East Tower refuse · level refuse rooms · chute · skip area',90,40),
  ('Recreation Deck: Pool and Spa','pool_spa','Sch 1: Outdoor Swimming Pool and Associated Areas','Pool · spa · surrounds · gates and fencing · plant and chemical store · sauna',40,50),
  ('Recreation Deck: BBQ and Outdoor Areas','bbq_outdoor','Sch 1: Barbecues and Outdoor Associated Areas','BBQ shelter · outdoor seating · artificial grass · surrounding paving',50,60),
  ('Gymnasium','gymnasium','Sch 1: Gymnasium','Gym interior · gym glass and balustrade · yoga area',60,70),
  ('Lawns, Gardens and Pathways','lawns_gardens','Sch 1: Lawns, Gardens and Pathways; cl 3.3','All garden beds · lawns · Prosperity Drive · Mantra Esplanade · foyer gardens · planter boxes',20,80),
  ('Common Area Lighting','common_lighting','Sch 1: Common Area Lighting','All common property lighting, internal and external',130,90),
  ('Fire Safety and Emergency Egress','fire_egress','Sch 1: Fire Escape Doors, Stairs and Landings; Emergency and Evacuation; cl 3.8','All fire stairs and landings · fire doors · fire booster cabinet · egress routes',80,100),
  ('Plant, Services and Infrastructure','plant_infrastructure','Sch 1: Infrastructure Services; Maintenance and Repairs; plant-room lines of General Areas; cl 3.5, 3.7, 3.15','Plant rooms · switchboard · comms rooms · fire and pump room · lift motor rooms · roof',100,110),
  ('General Areas, Common Property Toilets and Store Rooms','general_areas_toilets','Sch 1: General Areas; Common Property Toilets','Common property toilets · letterboxes · bio-retention area · rooftop · walkways · store rooms',110,120),
  ('Security, Access and Emergency Response','security_access','Sch 1: Security and Emergency; cl 5.3','CCTV · intercoms · access control · fire alarm panel · key store · building-wide',120,130)
) as v(name,cat,ref,zone,route,sort)
on conflict (building_id, name) do update set
  duty_category=excluded.duty_category, duty_reference=excluded.duty_reference,
  zone=excluded.zone, route_sort=excluded.route_sort, sort=excluded.sort, active=true;

insert into public.walkthrough_items
  (building_id, section_id, area, item, duty_reference, frequency, guidance, sort, active)
select 'ecd3d712-c949-4dec-b20c-9a5d36df0eb6'::uuid, s.id, v.sec, v.item, v.ref, v.freq,
       case when v.gen then 'No Schedule 1 line; rests on the general duties in cl 3.2/3.4. '
            || 'Weaker evidence than a cited Schedule 1 line with a frequency.' end,
       v.sort, true
  from (values
  ('Entrances, Reception Foyers and Lifts','Entry tiles and thresholds clean; no dirt line; dry before mats are replaced','Sch 1 Car Parks: clean car park lift lobbies, including glass, doors and associated areas','daily',false,10),
  ('Entrances, Reception Foyers and Lifts','Entry doors, frames and hinges clean; no rust or corrosion','Sch 1 Upper Residential Foyers: clean all Common Property doors and door frames including door hardware','monthly',false,20),
  ('Entrances, Reception Foyers and Lifts','Foyer glass and windows clean, inside and out','Sch 1 Upper Residential Foyers: clean all Accessible Common Property glass doors, windows, skirting boards and associated areas','weekly',false,30),
  ('Entrances, Reception Foyers and Lifts','Foyer furniture, counter tops, fixtures and fittings dusted, wiped and cleaned','Sch 1 Entrance, Reception Foyers and Lifts: dust, wipe, clean all foyer furniture, counter tops, fixtures and fittings','daily',false,40),
  ('Entrances, Reception Foyers and Lifts','Passenger lifts cleaned internally including lift facings and associated areas','Sch 1 Entrance, Reception Foyers and Lifts: clean passenger lifts internally including lift facings and associated areas','daily',false,50),
  ('Entrances, Reception Foyers and Lifts','Lift handrails and panels free of rust','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,60),
  ('Entrances, Reception Foyers and Lifts','Protective oil applied to all lift facings and fittings','Sch 1 Upper Residential Foyers: apply protective oil to all lift facings and fittings','weekly',false,70),
  ('Entrances, Reception Foyers and Lifts','Intercoms clean and free of rust (testing sits in group 13)','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,80),
  ('Entrances, Reception Foyers and Lifts','Car park and basement lift lobbies, including glass, doors and associated areas, clean','Sch 1 Car Parks: clean car park lift lobbies, including glass, doors and associated areas','daily',false,90),
  ('Upper Residential Foyers and Level Refuse Rooms','Floor-level foyers free of litter; rubbish room and chute spot cleaned','Sch 1 Upper Residential Foyers: check floor level foyers, pick-up litter and spot clean the rubbish room and chute as required','daily',false,100),
  ('Upper Residential Foyers and Level Refuse Rooms','All floor areas of upper level foyers vacuumed and mopped (twice weekly)','Sch 1 Upper Residential Foyers: vacuum/mop all floor areas of upper floor level foyers (twice weekly)','weekly',false,110),
  ('Upper Residential Foyers and Level Refuse Rooms','Common area tiles between units free of algae and dirt build-up','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,120),
  ('Upper Residential Foyers and Level Refuse Rooms','Cornices de-webbed and walls spot cleaned','Sch 1 Upper Residential Foyers: de-web cornices and spot clean walls','weekly',false,130),
  ('Upper Residential Foyers and Level Refuse Rooms','Common property glass doors, windows, skirting boards and associated areas clean','Sch 1 Upper Residential Foyers: clean all Accessible Common Property glass doors, windows, skirting boards and associated areas','weekly',false,140),
  ('Upper Residential Foyers and Level Refuse Rooms','Each floor level rubbish room and garbage chute entry swept, mopped, cleaned and sanitised','Sch 1 Upper Residential Foyers: sweep, mop, clean and sanitise each floor level rubbish room and entry to garbage chute','daily',false,150),
  ('Upper Residential Foyers and Level Refuse Rooms','Foyer level equipment cupboards clean','Sch 1 Upper Residential Foyers: clean all foyer level equipment cupboards','monthly',false,160),
  ('Upper Residential Foyers and Level Refuse Rooms','Lift door entrance plate grooves clean','Sch 1 Upper Residential Foyers: clean the lift door entrance plate grooves as required','monthly',false,170),
  ('Upper Residential Foyers and Level Refuse Rooms','Fire stair doors and fittings at each level free of cobwebs and marks','Sch 1 Fire Escape Doors, Stairs and Landings: sweep and clean fire escape stairs and landings, de-web all associated areas','monthly',false,180),
  ('Car Parks, Driveways and Entrances','Visitor car park surface free of green algae, staining and tile build-up','cl 3.2: clean paths and roads on the Common Property; driveways and paved areas are to be pressure cleaned',null,true,190),
  ('Car Parks, Driveways and Entrances','All basement drains and gutters clean','Sch 1 Car Parks: clean all basement drains and gutters','monthly',false,200),
  ('Car Parks, Driveways and Entrances','All driveway drains and gutters clean','Sch 1 Car Parks: clean all driveway drains and gutters','monthly',false,210),
  ('Car Parks, Driveways and Entrances','Fresh oil leaks cleaned to prevent staining on the common property driveways','Sch 1 Car Parks: clean fresh oil leaks to prevent staining on the Common Property driveways','monthly',false,220),
  ('Car Parks, Driveways and Entrances','Car parks kept clear of excess items','Sch 1 Car Parks: check the car parks are kept clear of excess items','monthly',false,230),
  ('Car Parks, Driveways and Entrances','Automatic vehicle entry/exit doors and gates watched through a full cycle','Sch 1 Car Parks: check the operation of automatic vehicle entry/exit doors/gates to car park (watch through full cycle)','weekly',false,240),
  ('Car Parks, Driveways and Entrances','Security car park doors and gates to the basement clean and maintained','Sch 1 Car Parks: clean and maintain security car park doors/gates to basement area','monthly',false,250),
  ('Car Parks, Driveways and Entrances','Emergency exit stairs from the basement car parking areas swept','Sch 1 Car Parks: sweep emergency exit stairs from basement car parking areas','monthly',false,260),
  ('Car Parks, Driveways and Entrances','Street entrances and driveways to the car parking area blower-vacced, swept and hosed','Sch 1 Car Parks: blower-vac/sweep/hose all street entrance and driveways to the car parking area','weekly',false,270),
  ('Car Parks, Driveways and Entrances','Basement driveways and all common areas hosed and swept','Sch 1 Car Parks: hose/sweep basement driveways and all common areas','weekly',false,280),
  ('Car Parks, Driveways and Entrances','Litter cleared from entrances, driveways and car park areas','Sch 1 Car Parks: clear litter from entrances, driveways and car park areas','daily',false,290),
  ('Car Parks, Driveways and Entrances','Resident and visitor vehicle parking and security monitored','Sch 1 Car Parks: monitor regularly residents and visitors vehicle parking and security','daily',false,300),
  ('Car Parks, Driveways and Entrances','Professional cleaning of the car parks arranged and supervised','Sch 1 Car Parks: arrange and supervise the cleaning of car parks','annually',false,310),
  ('Car Parks, Driveways and Entrances','Car wash bay signage and line marking current and correct','cl 3.14: supervise the carparking arrangements and keep the carparking areas in a clean and tidy condition',null,true,320),
  ('Car Parks, Driveways and Entrances','Bike storage area and cage clean; tiles and rust addressed','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,330),
  ('Rubbish Collection and Refuse Rooms','Recycling and general rubbish bins hosed and disinfected','Sch 1 Rubbish Collection: hose and disinfect the recycling/general rubbish bins','weekly',false,340),
  ('Rubbish Collection and Refuse Rooms','Refuse receptacles checked, emptied and bin liners replaced','Sch 1 Rubbish Collection: check refuse receptacles daily, empty and replace bin liners','daily',false,350),
  ('Rubbish Collection and Refuse Rooms','Rubbish bins checked and full bins rotated as necessary','Sch 1 Rubbish Collection: check rubbish bins daily, rotate full bins as necessary','daily',false,360),
  ('Rubbish Collection and Refuse Rooms','Recycling sorted and full bins rotated to provide access to empty bins','Sch 1 Rubbish Collection: sort recycle, rotate full bins to provide access to empty bins','daily',false,370),
  ('Rubbish Collection and Refuse Rooms','Garbage chute checked for obstructions','Sch 1 Rubbish Collection: check garbage chute for obstructions','daily',false,380),
  ('Rubbish Collection and Refuse Rooms','Deodorising system checked and serviced','Sch 1 Rubbish Collection: check and service the operation of the deodorising system','weekly',false,390),
  ('Rubbish Collection and Refuse Rooms','Skip bin placed out from the refuse room for collection and returned','Sch 1 Rubbish Collection: place out skip bin from refuse room for collection and return','weekly',false,400),
  ('Rubbish Collection and Refuse Rooms','Excess items not suitable for contractor skip bins removed','Sch 1 Rubbish Collection: arrange for the removal of all excess items that are not suitable for placing in contractor skip bins','monthly',false,410),
  ('Rubbish Collection and Refuse Rooms','Professional cleaning of the garbage chute arranged and supervised','Sch 1 Rubbish Collection: arrange and supervise the cleaning of the garbage chute by a contractor engaged by the Body Corporate','annually',false,420),
  ('Rubbish Collection and Refuse Rooms','Garbage collection areas kept clean and free of vermin','cl 3.9(b): ensure that garbage collection areas are kept clean and free of vermin',null,false,430),
  ('Rubbish Collection and Refuse Rooms','Occupant use of the garbage facilities monitored; breaches reported','cl 3.9(e): monitor whether occupants of the Building are properly using the garbage facilities and report any breaches',null,false,440),
  ('Rubbish Collection and Refuse Rooms','Refuse room floors, walls and roller doors clean','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,450),
  ('Rubbish Collection and Refuse Rooms','Refuse room fittings free of rust: hose reels, taps, fans','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,460),
  ('Rubbish Collection and Refuse Rooms','Comms and services room doors adjacent to refuse areas clean','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,470),
  ('Recreation Deck: Pool and Spa','Swimming pool waterline scrubbed to remove build-up','Sch 1 Pool: scrub swimming pool waterline to remove build-up as required','monthly',false,480),
  ('Recreation Deck: Pool and Spa','Sides of pool brushed to remove marks or stains','Sch 1 Pool: brush sides of pool to remove marks or stains','weekly',false,490),
  ('Recreation Deck: Pool and Spa','Swimming pool manually vacuumed and cleaned','Sch 1 Pool: manually vacuum and clean the swimming pool','weekly',false,500),
  ('Recreation Deck: Pool and Spa','Pool and spa floor surface: rust marks monitored and reported','cl 3.4(c): look for losses, breakdowns, defects and breakages',null,true,510),
  ('Recreation Deck: Pool and Spa','Complete clean of pool glass fencing and gates carried out','Sch 1 Pool: carry out complete clean of pool glass fencing and gates','monthly',false,520),
  ('Recreation Deck: Pool and Spa','Pool glass fencing and gates spot cleaned to remove finger marks','Sch 1 Pool: spot clean pool glass fencing and gates to remove finger marks','daily',false,530),
  ('Recreation Deck: Pool and Spa','Pool fencing checked; gate mechanisms tested','Sch 1 Pool: check pool fencing, test and check gate mechanisms','weekly',false,540),
  ('Recreation Deck: Pool and Spa','All poolside furniture clean and maintained','Sch 1 Pool: clean and maintain all poolside furniture','daily',false,550),
  ('Recreation Deck: Pool and Spa','Tiles beneath poolside furniture free of stains and marks','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,560),
  ('Recreation Deck: Pool and Spa','Pool area checked; rubbish picked up and disposed of','Sch 1 Pool: check the area, pick up and dispose of rubbish as required','daily',false,570),
  ('Recreation Deck: Pool and Spa','Pool skimmer baskets emptied','Sch 1 Pool: check daily, empty pool skimmer baskets as required','daily',false,580),
  ('Recreation Deck: Pool and Spa','Filter pressure checked and pool filter backwashed','Sch 1 Pool: check filter pressure and backwash pool filter as required','weekly',false,590),
  ('Recreation Deck: Pool and Spa','Pump filter baskets cleaned','Sch 1 Pool: clean pump filter baskets as required','monthly',false,600),
  ('Recreation Deck: Pool and Spa','All pool filtration equipment operating correctly','Sch 1 Pool: check and ensure the correct operation of all pool filtration equipment','daily',false,610),
  ('Recreation Deck: Pool and Spa','Pool heating system operating correctly and adjusted as required','Sch 1 Pool: check the correct operation of the pool heating system, adjust as required','daily',false,620),
  ('Recreation Deck: Pool and Spa','Swimming pool chemical balance tested, recorded and adjusted (chlorine and pH only)','Sch 1 Pool: test, record and adjust swimming pool chemical balance (chlorine & pH only)','daily',false,630),
  ('Recreation Deck: Pool and Spa','Pool safety signage checked, cleaned and updated','Sch 1 Pool: check, clean and update pool safety signage','monthly',false,640),
  ('Recreation Deck: Pool and Spa','Equipment room and chemical storage facility maintained in a clean and tidy condition','Sch 1 Pool: maintain the equipment room and chemical storage facility in a clean and tidy condition','weekly',false,650),
  ('Recreation Deck: Pool and Spa','Stainless steel hand railings clean','Sch 1 Pool: clean stainless steel hand railings','monthly',false,660),
  ('Recreation Deck: Pool and Spa','Pool surrounds swept, hosed and cleaned','Sch 1 Pool: sweep, hose and clean pool surrounds','weekly',false,670),
  ('Recreation Deck: Pool and Spa','Poolside covers de-webbed; accessible areas cleaned','Sch 1 Pool: de-web and clean accessible areas of poolside covers','monthly',false,680),
  ('Recreation Deck: Pool and Spa','Servicing and maintenance of the pool filtration system coordinated with the pool contractor','Sch 1 Pool: co-ordinate with the swimming pool contractor engaged in the servicing and maintenance of pool filtration system','monthly',false,690),
  ('Recreation Deck: Pool and Spa','Pool compliance certificate current','Sch 1 Infrastructure Services: obtain a certificate of compliance for the swimming pool','annually',false,700),
  ('Recreation Deck: Pool and Spa','Sauna operating correctly; all panels functional  [NO SCHEDULE 1 DUTY: see note]','No duty line in the agreement. Falls to cl 3.5 only if the Body Corporate directs.',null,true,710),
  ('Recreation Deck: BBQ and Outdoor Areas','Barbecues checked and cleaned as required','Sch 1 Barbecues: check barbecues daily, clean barbecues as required','daily',false,720),
  ('Recreation Deck: BBQ and Outdoor Areas','General area checked; litter picked up, rubbish bin emptied and area spot cleaned','Sch 1 Barbecues: check general area, pick up litter, empty rubbish bin and spot clean area','daily',false,730),
  ('Recreation Deck: BBQ and Outdoor Areas','Barbecue drip trays cleaned or replaced','Sch 1 Barbecues: clean/replace barbecue drip trays','weekly',false,740),
  ('Recreation Deck: BBQ and Outdoor Areas','Barbecue cover and seating areas de-webbed, dusted, hosed and cleaned','Sch 1 Barbecues: de-web, dust, hose and clean Accessible areas of barbecue cover and seating areas','monthly',false,750),
  ('Recreation Deck: BBQ and Outdoor Areas','Paved and tiled barbecue areas swept, hosed, mopped and cleaned','Sch 1 Barbecues: sweep/hose/mop and clean paved/tiled barbecue areas','weekly',false,760),
  ('Recreation Deck: BBQ and Outdoor Areas','Tables, chairs and associated furniture cleaned with suitable cleaning products','Sch 1 Barbecues: clean tables, chairs and associated furniture with suitable cleaning products','daily',false,770),
  ('Recreation Deck: BBQ and Outdoor Areas','All stainless steel polished with a suitable protective product','Sch 1 Barbecues: polish all stainless steel with a suitable protective product','weekly',false,780),
  ('Recreation Deck: BBQ and Outdoor Areas','Benches and sink checked and cleaned as required','Sch 1 Barbecues: check benches and sink daily, clean as required','daily',false,790),
  ('Recreation Deck: BBQ and Outdoor Areas','Barbecue grills, doors, handles and housing free of rust and corrosion','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,800),
  ('Recreation Deck: BBQ and Outdoor Areas','BBQ wall and surrounds clean','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,810),
  ('Recreation Deck: BBQ and Outdoor Areas','Professional cleaning of the artificial grass areas arranged and supervised','Sch 1 General Areas: arrange and supervise the professional cleaning of the artificial grass areas','annually',false,820),
  ('Gymnasium','Gym equipment wiped down, cleaned and disinfected','Sch 1 Gymnasium: wipe down, clean and disinfect gym equipment','daily',false,830),
  ('Gymnasium','All glass spot cleaned, floor areas spot cleaned and correct operation of all equipment checked','Sch 1 Gymnasium: spot clean all glass, spot clean the floor areas and check the correct operation of all equipment','daily',false,840),
  ('Gymnasium','Full vacuum of all floor areas completed','Sch 1 Gymnasium: complete a full vacuum of all floor areas','weekly',false,850),
  ('Gymnasium','All accessible glass areas including windows, doors, frames and mirrors clean','Sch 1 Gymnasium: clean all Accessible glass areas including windows, doors, frames and mirrors','weekly',false,860),
  ('Gymnasium','Walls, cornices and skirting boards wiped down and spot cleaned with a suitable non-abrasive agent','Sch 1 Gymnasium: wipe down and spot clean all walls, cornices and skirting boards using a suitable non-abrasive cleaning agent such as eucalyptus oil and a soft cloth','weekly',false,870),
  ('Gymnasium','Air conditioning filters and vents cleaned','Sch 1 Gymnasium: clean air conditioning filters/vents','monthly',false,880),
  ('Gymnasium','All entertainment equipment clean and operating correctly','Sch 1 Gymnasium: clean and ensure the correct operation of all entertainment equipment','daily',false,890),
  ('Gymnasium','Service and testing of gym equipment arranged; access provided','Sch 1 Gymnasium: arrange, provide access for the service and testing of gym equipment','quarterly',false,900),
  ('Gymnasium','Gym equipment free of rust','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,910),
  ('Gymnasium','Sliding door tracks clean','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,920),
  ('Gymnasium','Door handles, locks and taps free of rust and corrosion','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,930),
  ('Gymnasium','Cobwebs removed; exterior glass and balustrade clean and free of bird droppings','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,940),
  ('Lawns, Gardens and Pathways','Weeds sprayed and controlled in all common property gardens and paved areas','Sch 1 Lawns, Gardens and Pathways: spray and control weeds in all Common Property gardens and paved areas, etc.','monthly',false,950),
  ('Lawns, Gardens and Pathways','All common property garden areas weeded','Sch 1 Lawns, Gardens and Pathways: weed all Common Property garden areas','monthly',false,960),
  ('Lawns, Gardens and Pathways','All gardens checked and build-up of leaf litter removed','Sch 1 Lawns, Gardens and Pathways: check all gardens to remove build-up of leaf litter','monthly',false,970),
  ('Lawns, Gardens and Pathways','Re-mulching of gardens arranged and supervised; access provided','Sch 1 Lawns, Gardens and Pathways: provide access and supervise the re-mulching of gardens when required','annually',false,980),
  ('Lawns, Gardens and Pathways','All hedges and planter boxes trimmed and shaped; trimmings cleaned up and disposed of','Sch 1 Lawns, Gardens and Pathways: trim and shape all hedges/planter boxes, clean up and dispose of trimmings','weekly',false,990),
  ('Lawns, Gardens and Pathways','Garden irrigation system checked and maintained; plants not covered hand watered','Sch 1 Lawns, Gardens and Pathways: check and maintain the operation of the garden irrigation system, hand water any plants not covered by this system','weekly',false,1000),
  ('Lawns, Gardens and Pathways','All gardens, plants, shrubs and palms hand fertilised as required','Sch 1 Lawns, Gardens and Pathways: hand fertilise all gardens, plants, shrubs and palms as required','quarterly',false,1010),
  ('Lawns, Gardens and Pathways','Damaged plants, shrubs or trees replaced or replanted','Sch 1 Lawns, Gardens and Pathways: replace/replant damaged plants, shrubs or trees','as_required',false,1020),
  ('Lawns, Gardens and Pathways','All plants and shrubs sprayed for pests and diseases','Sch 1 Lawns, Gardens and Pathways: spray all plants and shrubs for pests and diseases','quarterly',false,1030),
  ('Lawns, Gardens and Pathways','Seasonal pruning of shrubs and gardens carried out','Sch 1 Lawns, Gardens and Pathways: carry out seasonal pruning of shrubs and gardens','quarterly',false,1040),
  ('Lawns, Gardens and Pathways','All garden paths and access ways blower-vacced and swept','Sch 1 Lawns, Gardens and Pathways: blowervac/sweep all garden paths and access ways','weekly',false,1050),
  ('Lawns, Gardens and Pathways','All garden areas and artificial lawns checked; litter picked up and disposed of','Sch 1 Lawns, Gardens and Pathways: check all garden areas and artificial lawns, pick up litter and dispose','daily',false,1060),
  ('Lawns, Gardens and Pathways','Planter box drains and associated areas clean and maintained','Sch 1 Maintenance and Repairs: clean and maintain the planter box drains and associated areas','monthly',false,1070),
  ('Lawns, Gardens and Pathways','Lawns mown, watered, fertilised, top-dressed and aerated; kept neat, level and weed free','cl 3.3: keep the lawns and gardens on the Common Property in good condition',null,false,1080),
  ('Lawns, Gardens and Pathways','Plants not touching walls or overhanging paths','cl 3.3(e): pruning as recommended for particular plants to maintain an appropriate size, shape and to encourage growth',null,false,1090),
  ('Common Area Lighting','All common property lights inspected and accessible faulty bulbs/tubes replaced','Sch 1 Common Area Lighting: inspect all Common Property lights and replace accessible faulty bulbs/tubes as required','weekly',false,1100),
  ('Common Area Lighting','Replacement of inaccessible lights arranged and supervised','Sch 1 Common Area Lighting: arrange and supervise the replacement of inaccessible lights','monthly',false,1110),
  ('Common Area Lighting','Common property lights checked, cleaned and insects removed','Sch 1 Common Area Lighting: check, clean and remove insects from Common Property lights','monthly',false,1120),
  ('Common Area Lighting','Light and power timers adjusted to meet required lighting times and following power failures','Sch 1 Common Area Lighting: adjust light and power timers when necessary to meet required lighting times and following power failures','quarterly',false,1130),
  ('Common Area Lighting','External and pathway lighting operating at dusk','cl 3.4(b): find lights that need to be replaced',null,true,1140),
  ('Fire Safety and Emergency Egress','All access doors checked; specialist repairs arranged when required','Sch 1 Fire Escape Doors: check all access doors, arrange specialist repairs when required','weekly',false,1150),
  ('Fire Safety and Emergency Egress','Fire escape stairs and landings checked; litter picked up and spot cleaned','Sch 1 Fire Escape Doors: check fire escape stairs and landings, pick up litter, spot clean as required','weekly',false,1160),
  ('Fire Safety and Emergency Egress','Self-closing exit doors checked; any malfunctions reported','Sch 1 Fire Escape Doors: check self-closing exit doors, report of any malfunctions','monthly',false,1170),
  ('Fire Safety and Emergency Egress','Fire escape stairs and landings swept and cleaned; all associated areas de-webbed','Sch 1 Fire Escape Doors: sweep and clean fire escape stairs and landings, de-web all associated areas','monthly',false,1180),
  ('Fire Safety and Emergency Egress','All handrails and balustrades wiped down','Sch 1 Fire Escape Doors: wipe down all handrails and balustrades','monthly',false,1190),
  ('Fire Safety and Emergency Egress','Building emergency evacuation signage checked and updated as required','Sch 1 Emergency and Evacuation: check building emergency evacuation signage, update as required (as per Building Fire Safety Regulations 2008)','quarterly',false,1200),
  ('Fire Safety and Emergency Egress','Building evacuation procedures completed and evacuation plan reviewed','Sch 1 Emergency and Evacuation: complete building evacuation procedures and review evacuation plan (as per Building Fire Safety Regulations 2008)','annually',false,1210),
  ('Fire Safety and Emergency Egress','Fire safety requirements notified to all occupants; minor breaches remedied','cl 3.8: ensure that fire safety requirements are notified to all occupants; where possible remedy minor breaches of the fire safety regulations',null,false,1220),
  ('Fire Safety and Emergency Egress','Egress routes clear of obstruction and stored items','cl 3.8: monitor the Body Corporate''s compliance with fire safety regulations',null,false,1230),
  ('Fire Safety and Emergency Egress','Fire booster cabinet interior clean; cobwebs and rust removed; door frames clean','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,1240),
  ('Plant, Services and Infrastructure','Testing of installed water back-flow devices arranged','Sch 1 Infrastructure Services: arrange the testing of installed water back-flow devices','annually',false,1250),
  ('Plant, Services and Infrastructure','Testing and tagging of common property electrical cords: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the testing and tagging of common property electrical cords','annually',false,1260),
  ('Plant, Services and Infrastructure','Certificates of registration for registered plant and equipment obtained and retained on file','Sch 1 Infrastructure Services: obtain and retain on file all certificates of registration for registered plant and equipment','annually',false,1270),
  ('Plant, Services and Infrastructure','Inspection and maintenance of unit entry doors: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the inspection and maintenance of unit entry doors','annually',false,1280),
  ('Plant, Services and Infrastructure','Maintenance and servicing of automatic entry/exit gates: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the maintenance and servicing of the automatic entry/exit gates','quarterly',false,1290),
  ('Plant, Services and Infrastructure','Maintenance and testing of smoke doors: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the maintenance and testing of smoke doors','annually',false,1300),
  ('Plant, Services and Infrastructure','Correct operation of lift-well pumps ensured; access provided for servicing and maintenance','Sch 1 Infrastructure Services: ensure the correct operation of lift-well pumps, provide access for servicing and maintenance','quarterly',false,1310),
  ('Plant, Services and Infrastructure','Maintenance and testing of all fire doors and self-closers: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the maintenance and testing of all fire doors and self-closers','biannually',false,1320),
  ('Plant, Services and Infrastructure','Maintenance and testing of fire extinguishers and hose reels: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the maintenance and testing of the fire extinguisher and hose reels','biannually',false,1330),
  ('Plant, Services and Infrastructure','Maintenance and testing of the standby generator: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the maintenance and testing of the standby generator','quarterly',false,1340),
  ('Plant, Services and Infrastructure','Operation and maintenance of the passenger lifts: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the operation and maintenance of the passenger lifts','monthly',false,1350),
  ('Plant, Services and Infrastructure','Testing and tagging of safety anchor points: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the testing and tagging of safety anchor points','annually',false,1360),
  ('Plant, Services and Infrastructure','Testing of fire alarm systems: thermal and smoke detectors: access provided and recorded','Sch 1 Infrastructure Services: provide access and record the testing of fire alarm systems - thermal and smoke detectors','biannually',false,1370),
  ('Plant, Services and Infrastructure','Fire and pump equipment room checked, swept and cleaned','Sch 1 General Areas: check, sweep and clean the fire and pump equipment room','monthly',false,1380),
  ('Plant, Services and Infrastructure','Main switchboard and comms rooms checked, swept and cleaned','Sch 1 General Areas: check, sweep and clean the main switchboard/comms rooms','monthly',false,1390),
  ('Plant, Services and Infrastructure','All store, plant, diesel and lift motor rooms swept, cleaned and tidied','Sch 1 General Areas: sweep, clean and tidy all store/plant/diesel/and lift motor rooms','monthly',false,1400),
  ('Plant, Services and Infrastructure','Cleaning of exposed pipe work in the basement car park arranged and coordinated','Sch 1 Maintenance and Repairs: arrange and co-ordinate equipped contractors for the cleaning of exposed pipe work in basement car park','annually',false,1410),
  ('Plant, Services and Infrastructure','Cleaning of not-Accessible common property glass by a qualified contractor arranged and coordinated','Sch 1 Maintenance and Repairs: arrange and co-ordinate the cleaning of not Accessible Common Property glass by a qualified contractor','annually',false,1420),
  ('Plant, Services and Infrastructure','Access for common property pest control arranged and coordinated','Sch 1 Maintenance and Repairs: arrange and co-ordinate access for the Common Property pest control','quarterly',false,1430),
  ('Plant, Services and Infrastructure','All complex signage clean and maintained','Sch 1 Maintenance and Repairs: clean and maintain all the complex signage','monthly',false,1440),
  ('Plant, Services and Infrastructure','Urgent minor repairs not covered by a contract arranged and coordinated','Sch 1 Maintenance and Repairs: arrange and co-ordinate any urgent minor repairs not covered by a contract','weekly',false,1450),
  ('Plant, Services and Infrastructure','Minor repairs to common property not requiring a skilled tradesperson carried out','Sch 1 Maintenance and Repairs: carry out minor repairs to Common Property that do not require the services of a skilled tradesperson','weekly',false,1460),
  ('Plant, Services and Infrastructure','Contractors and tradesmen instructed and liaised with when onsite for repair work','Sch 1 Maintenance and Repairs: instruct and liaise with contractors / tradesmen when onsite for repair work on behalf of Body Corporate','weekly',false,1470),
  ('Plant, Services and Infrastructure','Service contract register current; expiry dates and non-compliance advised','cl 3.15: maintain a register of service contracts including term, fees payable and the expiry date, and advise the Body Corporate of non-compliance and of the expiry date',null,false,1480),
  ('General Areas, Common Property Toilets and Store Rooms','Toilet doors, door handles, partitions and light switches wiped over','Sch 1 Common Property Toilets: wipe over doors and door handles, partitions and light switches','daily',false,1490),
  ('General Areas, Common Property Toilets and Store Rooms','Hand basins, taps, mirrors and all associated areas cleaned','Sch 1 Common Property Toilets: clean hand basins, taps, mirrors and all associated areas','daily',false,1500),
  ('General Areas, Common Property Toilets and Store Rooms','Toilet areas spot checked during the day and consumables replaced','Sch 1 Common Property Toilets: spot check the toilet areas during the day and replace consumables','daily',false,1510),
  ('General Areas, Common Property Toilets and Store Rooms','Shower and associated areas cleaned','Sch 1 Common Property Toilets: clean the shower and associated areas','daily',false,1520),
  ('General Areas, Common Property Toilets and Store Rooms','All tiled floors mopped and disinfected','Sch 1 Common Property Toilets: mop and disinfect all tiled floors','daily',false,1530),
  ('General Areas, Common Property Toilets and Store Rooms','Toilet cisterns, bowls and seats cleaned','Sch 1 Common Property Toilets: clean toilet cistern, bowls and seats','daily',false,1540),
  ('General Areas, Common Property Toilets and Store Rooms','All wall areas de-webbed, wiped down and cleaned','Sch 1 Common Property Toilets: de-web, wipe down and clean all wall areas','weekly',false,1550),
  ('General Areas, Common Property Toilets and Store Rooms','Servicing of hygienic facilities arranged and coordinated','Sch 1 Common Property Toilets: arrange and co-ordinate the servicing of hygienic facilities','monthly',false,1560),
  ('General Areas, Common Property Toilets and Store Rooms','Removalists coordinated for change-over of tenancies to prevent damage to common property','Sch 1 General Areas: co-ordinate removalists for the change-over of tenancies to prevent any damage to common property (including lift erection and removing of lift curtains)','weekly',false,1570),
  ('General Areas, Common Property Toilets and Store Rooms','Rubbish and litter removed from the bio-retention area','Sch 1 General Areas: remove rubbish/litter from the bio-retention area','weekly',false,1580),
  ('General Areas, Common Property Toilets and Store Rooms','Lifts padded for removalists and tradespersons; pads removed and lifts cleaned when completed','Sch 1 General Areas: pad lifts for removalists, tradespersons and remove pads and clean lifts when completed','monthly',false,1590),
  ('General Areas, Common Property Toilets and Store Rooms','Paths and roads on the common property clean; driveways and paved areas pressure cleaned','cl 3.2: clean paths and roads on the Common Property; driveways and paved areas are to be pressure cleaned',null,false,1600),
  ('General Areas, Common Property Toilets and Store Rooms','Letterboxes clean and tidy','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,1610),
  ('General Areas, Common Property Toilets and Store Rooms','Bird and animal activity: nests, droppings: identified and addressed','cl 3.4: inspect the Common Property daily to ensure the Common Property is clean',null,true,1620),
  ('General Areas, Common Property Toilets and Store Rooms','Rooftop common property areas clean','cl 3.2: clean the Accessible parts of the buildings on the Common Property',null,true,1630),
  ('General Areas, Common Property Toilets and Store Rooms','Walkway brickwork and perimeter surfaces free of algae and build-up','cl 3.2: clean paths and roads on the Common Property',null,true,1640),
  ('Security, Access and Emergency Response','Daily security check of the common property completed','Sch 1 Security and Emergency: complete a daily security check of the Common Property','daily',false,1650),
  ('Security, Access and Emergency Response','Ongoing operation of the CCTV security system and cameras monitored and ensured','Sch 1 Security and Emergency: monitor and ensure the ongoing operation of the CCTV security system and cameras','daily',false,1660),
  ('Security, Access and Emergency Response','CCTV security system reviewed to identify incidents; images downloaded as required','Sch 1 Security and Emergency: review CCTV security system to identify incidents, download images as required','monthly',false,1670),
  ('Security, Access and Emergency Response','Intercoms and communication systems tested; any repairs arranged','Sch 1 Security and Emergency: test intercoms and communication systems and arrange any repairs','weekly',false,1680),
  ('Security, Access and Emergency Response','Fire alarm control panel and systems operation inspected; any alarms or malfunctions reported','Sch 1 Security and Emergency: inspect fire alarm control panel and systems operation, report any alarms or malfunctions','daily',false,1690),
  ('Security, Access and Emergency Response','Swipe cards and fobs recorded, programmed and re-coded for the security access system','Sch 1 Security and Emergency: record, program and re-code swipe cards/fobs for security access system','weekly',false,1700),
  ('Security, Access and Emergency Response','Register of master keys and keys under management maintained','Sch 1 Security and Emergency: maintain a register of master keys and keys under management','monthly',false,1710),
  ('Security, Access and Emergency Response','Annual audit of master keys and security keys completed','Sch 1 Security and Emergency: complete an annual audit of master keys and security keys','annually',false,1720),
  ('Security, Access and Emergency Response','Security issues reported to the Body Corporate','Sch 1 Security and Emergency: report to the Body Corporate on any security issues','weekly',false,1730),
  ('Security, Access and Emergency Response','Log of security issues and by-law breaches maintained','Sch 1 Management Administrative Services: maintain a log of any security issues and By-law breaches','weekly',false,1740),
  ('Security, Access and Emergency Response','Emergencies and callouts responded to; building security supervised and disturbances attended','Sch 1 Security and Emergency: respond to emergencies and callouts; supervise building security and attend any disturbances','as_required',false,1750),
  ('Security, Access and Emergency Response','A responsible person contactable at all reasonable times; number displayed prominently on common property','cl 5.3: ensure that at all reasonable times an appropriately responsible person is able to be contacted',null,false,1760)
) as v(sec,item,ref,freq,gen,sort)
  join public.walkthrough_sections s on s.building_id = 'ecd3d712-c949-4dec-b20c-9a5d36df0eb6'::uuid and s.name = v.sec
on conflict (building_id, item) do update set
  section_id=excluded.section_id, area=excluded.area, duty_reference=excluded.duty_reference,
  frequency=excluded.frequency, guidance=excluded.guidance, sort=excluded.sort, active=true;
